// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtVWmPOp7jpMgcdcvxizr7PG7qfXlj_ew',
    appId: '1:229748420116:web:7e32a8cf7e0b084e5ac101',
    messagingSenderId: '229748420116',
    projectId: 'fitjourney-a8e3e',
    authDomain: 'fitjourney-a8e3e.firebaseapp.com',
    storageBucket: 'fitjourney-a8e3e.appspot.com',
    measurementId: 'G-04JJKBHBND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFmJWP5_ZAHNSpceYh_v0d9x8SE7_bTxY',
    appId: '1:229748420116:android:bdc7921f07fc64a45ac101',
    messagingSenderId: '229748420116',
    projectId: 'fitjourney-a8e3e',
    storageBucket: 'fitjourney-a8e3e.appspot.com',
  );
}
